name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.2.20176.6
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@master
      with:
        host: http://ip172-18-0-84-bvt3b7434gag00fibocg-9000.direct.labs.play-with-docker.com
        login: ce9fdf5ea6b7ed097664048a7dafaa2ed9c2d3cb
